### ISSUE TITLE
Incorrect reward shown in the screenshot

### ISSUE THREAD

**Issue by aravic** [cuayahuitl/SimpleDS#1]
In the screenshot the rewards don't seem to follow the following formula given in the paper : 
R(s, a, s') = (CR x w) + ( DR x (1 - w) ) - DL with DL = 0.1.
Some of the rewards are even more than 0.9.
For instance the reward after salutation(closing) is around 29.

**Comment by cuayahuitl** [comment]
I haven't seen that. Are you using the original version that is in GitHub
or a modified one?

Can you try plotting your learning curve?

> octave scripts/plotdata.m results/english/simpleds-output.txt

You should get something similar to this one:
https://github.com/cuayahuitl/SimpleDS/blob/master/results/english/simpleds-output.png

Thanks!

**Comment by aravic** [comment]
Yes. That parts right. 
I meant the reward shown in  screenshots/Screenshot-SimpleDS-test.png
Thanks.

**Comment by cuayahuitl** [comment]
I see. That screenshot must have been an earlier version that the one
reported in the paper. I should update it. Thanks for the pointer!
