### ISSUE TITLE
what is usage of data/english/dialogueN.txt

### ISSUE THREAD

**Issue by yoosan** [cuayahuitl/SimpleDS#3]
Hi, I have a question about the usage of dialogues.

The dialogues in data/language file is just used to train a classifier?

**Comment by cuayahuitl** [comment]
Hi Yao,

the unique words in those dialogues are used as features in the system. In
addition, those dialogues are used to train a statistical classifier that
SimpleDS uses to (1) select the most likely actions given word-based
features, and (2) provide data-like rewards. Notice that during training
the system will potentially induce its behaviour from a large number of
different dialogues, derived from combining different system responses with
semi-random user responses.

I hope this answers your question.
Best,
Heriberto

**Comment by yoosan** [comment]
Thanks Heriberto,

I got your meaning since i have read your paper `SimpleDS`. The dialog examples in `data/english` is used to compute the rewards, and to narrow action space depending  on probability threshold?  We know that deep Q-learining with experience replay is well suited for unsupervised learning, there is no need for preparing supervised data. These 6 dialogs are not the training examples in RL.

**Comment by wxtyixiao** [comment]
Hi, I have a question about the running procedure of runclient.js.

During the training, the policy and the output hadn't been saved in results. Is it right?
<img width="463" alt="_20180927172202" src="https://user-images.githubusercontent.com/24651880/46136543-70426c00-c27a-11e8-9887-8133b6d72463.png">

**Comment by wxtyixiao** [comment]
![image](https://user-images.githubusercontent.com/24651880/46136595-88b28680-c27a-11e8-8bc8-45dfb6829916.png)

**Comment by cuayahuitl** [comment]
Hello Xiaoting,

I don't know if I have already answered your question, but please set the
number of dialogues to a larger number. One dialogue is for testing
purposes, and the trained policy (according to the config.txt file) is
saved every 2500 dialogues. Hope it helps.

Best regards,
Heriberto
